### ISSUE TITLE
Parsing JSON which isn't conforming to RFC

### ISSUE THREAD

**Issue by akamaus** [bos/aeson#100]
There is a bunch of places on the web there you can find JSON which deviate from the standard.
A rather typical example would be { a: 42, b: 'hello world' }

I'd like to see Aeson's parser relaxed to cover such bad examples. Your thoughts?

**Comment by jsdw** [comment]
I know this issue is closed, but just my 2 pence; I am using Aeson's json parser directly to parse JSON in  as arguments to commands in a CLI I'm writing. In this case, it's simply a little better for the users who are typing the JSON to not have to worry about quotes around keys when providing the relevant input.

This feature isn't super high on my current todo list but I may look to submit a patch when I get around to it if I can see a simple enough solution!
