### ISSUE TITLE
Can we get better error messages?

### ISSUE THREAD

**Issue by nh2** [bos/aeson#113]
Today I tried to decode a "1" to an Int, but it failed, because apparently only objects and arrays are top-level JSON (this is not said explicitly on http://json.org though).

```
eitherDecode ("1") :: Either String Int
Left "Failed reading: satisfy"
```

This took me quite some time. Is it possible to have slightly more informative error messages than this?

**Comment by bos** [comment]
This is now resolved.

```haskell
>>> eitherDecode "[]" :: Either String Int
Left "Error in $: when expecting a Int, encountered Array instead"
```

**Comment by nh2** [comment]
Nice!

**Comment by maeehart** [comment]
I had again the same error message
`Error reading file elm-package.json:
    Failed reading: satisfy`
 my json is 
`{
    "version": "1.0.0",
    "summary": "Website for the Nonlinear optimization course at the University of Jyväskylä, spring 2016",
    "repository": "None",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "3.0.0 <= v < 4.0.0",
	"evancz/elm-html": "4.0.2 <= v < 5.0.0",
	"evancz/elm-markdown": "2.0.0 <= v < 3.0.0",
    },
    "elm-version": "0.16.0 <= v < 0.17.0"
}`

Any help?

The version is
`elm-make 0.16 (Elm Platform 0.16.0)`
so it is greater than 0.10. which was mentioned to have this fixed.

**Comment by maximkulkin** [comment]
@maeehart Version of Elm programming language/compiler/platform has nothing to do with version of Haskell JSON library (this library). From the source code of elm-package you can clearly see that as of version 0.16 it still uses "aeson >= 0.7 && < 0.9" (https://github.com/elm-lang/elm-package/blob/0.16/elm-package.cabal#L57). You should write an issue to [elm-package](https://github.com/elm-lang/elm-package) to update version of aeson library to 0.10 or higher to resolve this.

**Comment by JoeShanahanT** [comment]
I hope these are still read..

I had an issue today where I saw this error. Having never seen it before (and seeing here that it was 'fixed' - although not applicable to my situation) it took me some time to track down what my problem was.

It was a simple case of my JSON not being valid after me making an innocent minor change after already checking for validity. Is it possible for Aeson to at least state that the attempted parse failed because the supplied JSON is invalid, rather than just saying `Error in $: 34: Failed reading: satisfy`.

If someone could point to the place where this is handling I could have a go at doing it myself?

**Comment by phadej** [comment]
@JoeShanahanT https://github.com/bos/aeson/blob/2bc6f22f164d172d0d77d878422b67433a57a9d8/Data/Aeson/Parser/Internal.hs#L260

The `satisfy` is in the `msg` which we get from `attoparsec`. Maybe adding `<?>` in `json` and `value` parsers above in the file could improve some of the errors.

**Comment by bergmark** [comment]
@JoeShanahanT please file a new issue for this! I consider all uninformative error messages bugs.

**Comment by JoeShanahanT** [comment]
Done 👍
