### ISSUE TITLE
deriveJSON's generated instances have awkward contexts

### ISSUE THREAD

**Issue by russetkoala** [bos/aeson#137]
Motivating example:

```
{-# LANGUAGE FlexibleContexts, TypeFamilies #-}
import Data.Aeson

data Tagged s = Tagged { tag :: Tag s
                       }

class (FromJSON (Tag s), ToJSON (Tag s)) => C s where
    type Tag s
    fromTag :: Tag s -> Tagged s

instance C s => ToJSON (Tagged s) where
    toJSON = toJSON . tag

instance C s => FromJSON (Tagged s) where
    parseJSON = fmap fromTag . parseJSON

data Foo s = Spam (Tagged s) | Eggs
```

It would be nice to be able to use deriveJSON to generate ToJSON and FromJSON instances for Foo. However, attempting to do so produces instances that look like this:

```
instance ToJSON s => ToJSON (Foo s) where
    ...
```

but there's no need to have a ToJSON constraint on Foo's parameter: ToJSON (Tagged s) suffices.

For this example, it would be enough for deriveJSON to just not inspect the parameter to the constructor deeply: for an ADT `data A p_1 p_2 ... = A a_1 a_2 ... | B b_1 ... | ...`, the generated instances look like `instance (ToJSON a_1, ToJSON a_2, ToJSON b_1, ...) => ToJSON (A p_1 p_2 ...)`. I -think- this will work for all ADTs, but I am not sure about GADTs. A general solution would be adding a field to Options to control how the instance constraints are generated, presumably of type [Name] -> [Cxt].

**Comment by bergmark** [comment]
Is there anything here that #346 did not resolve?

**Comment by RyanGlScott** [comment]
#346 wasn't aimed to fix this. The criterion it uses for determining whether a type variable should have a `ToJSON`/`FromJSON` context is quite naïve: it just checks if it has kind `*`. So the above example would still have a spurious `ToJSON/FromJSON` context (unless `PolyKinds` isn't enabled).

There are many more awkward corner cases to consider when deriving instance contexts, too, and I certainly don't want to write the code that mimics what GHC currently does, since it's quite complex. (See also https://github.com/mboes/th-lift/issues/20#issuecomment-157955277)

**Comment by bergmark** [comment]
Thanks for the clarification!

Let's just close this then, the issue has been open for 3 years so it does not seem like a high priority.
