### ISSUE TITLE
deriveJSON for Either a b

### ISSUE THREAD

**Issue by itchyny** [bos/aeson#188]
I'm new to this library and I found that `deriveJSON` is very powerful.

I noticed that `Maybe a` in a data field works as expected.
```haskell
{-# LANGUAGE TemplateHaskell, OverloadedStrings #-}
import Data.Aeson
import Data.Aeson.TH

data D = D { number :: Maybe Int }
        deriving (Eq, Show)

$(deriveJSON defaultOptions ''D)

main :: IO ()
main = do
  print (decode "{}" :: Maybe D)
  print (decode "{\"number\": 10}" :: Maybe D)
```
The result is
```
Just (D {number = Nothing})
Just (D {number = Just 10})
```

However, I could not use `Either`.
```haskell
{-# LANGUAGE TemplateHaskell, OverloadedStrings #-}
import Data.Aeson
import Data.Aeson.TH

data D = D { number :: Either Int String }
        deriving (Eq, Show)

$(deriveJSON defaultOptions ''D)

main :: IO ()
main = do
  print (decode "{\"number\": 10}" :: Maybe D)
  print (decode "{\"number\": \"30\" }" :: Maybe D)
```
The result is
```
Nothing
Nothing
```

If the result was like the following, it would be nice.
```
Just (D {number = Left 10})
Just (D {number = Right "30"})
```

Moreover, it would be nice if we can use deriveJSON for a data like the following.
```haskell
data D = D { number :: Maybe (Either Int String) }
```

**Comment by mgsloan** [comment]
There are a couple good reasons not to implement this:

1) What do you do about "Either Int Int" ? 

2) This would change the encoding of `Either`, which would break data compatibility between aeson versions.

**Comment by itchyny** [comment]
Reasoning as follows. Consider a simple configuration syntax accepting a dictionary. What if I want to accept both a number and an array of numbers with the same key?
```yaml
position: 10
```
```yaml
position:
  - 10
  - 20
  - 30
```
We cannot implement this with deriveJSON unfortunately.

**Comment by mgsloan** [comment]
Sure, but that can easily be implemented by writing code for it - not everything needs to be derived.  Since `Either` has an existing serialization which can handle `Either a a`, this is certainly a better default.

You could add your own datatype for such functionality, but note there will be no way to enforce that the encodings of the two datatypes will allow distinction between `Left` and `Right`.  Even if Haskell had type inequality, it wouldn't be possible to know that the encodings of the two types don't use indistinguishable JSON.
