### ISSUE TITLE
`cabal install aeson` fails on stage-1 (cross) compilers, can TH be disabled?

### ISSUE THREAD

**Issue by themasterchef** [bos/aeson#239]
I'm trying to cross-compile a larger library for a non-x86_64 CPU arch, which uses Aeson as a dependency, using `cabal install`. Said larger library never uses the Template Haskell features of Aeson, but for some reason cabal is throwing errors about them anyway. When I tried reducing the problem scope to just `cabal install aeson`, the error is as follows:

```
Configuring aeson-0.8.0.2...
Building aeson-0.8.0.2...
Preprocessing library aeson-0.8.0.2...
ghc: Data/Aeson/TH.hs:2:46-60: Template Haskell requires GHC with interpreter support
    Perhaps you are using a stage-1 compiler?
```

The TH features are evidently being read by the compiler even though I have no need of them. Is there some way to get cabal install / ghc to totally leave the TH portions of Aeson alone?

**Comment by mgsloan** [comment]
The error message points to [this line](https://github.com/bos/aeson/blob/67ea6491600cae9a6bf8a87a558badadffcac791/Data/Aeson/TH.hs#L2) which has the `TemplateHaskell` extension.  Since `Data.Aeson.TH` isn't used by any of the other modules (based on [this search](https://github.com/bos/aeson/search?p=1&q=Data.Aeson.TH&utf8=%E2%9C%93)), you should be able to simply remove the module from the cabal file here: https://github.com/bos/aeson/blob/master/aeson.cabal#L90

**Comment by bos** [comment]
This seems like a GHC/Cabal issue. While we could add a flag to disable TH in aeson, flags are very fragile and don't work at all when indirect dependencies need to be installed.

**Comment by themasterchef** [comment]
Thanks for the solution, it does indeed work if you are compiling Aeson by itself from source.

The trouble comes when Aeson is a dependency of another project that gets dragged in by Cabal - and as you say there is no easy and reliable way to indicate to the top-level project that if it should happen to require Aeson somewhere down its dependency tree then it should ignore the TH bit.
