### ISSUE TITLE
encodeToTextBuilder hangs

### ISSUE THREAD

**Issue by andrewthad** [bos/aeson#246]
Here is a minimal example:

    import Prelude
    import Data.Aeson
    import Data.Aeson.Encode
    import Data.Text.Lazy.Builder as Builder
    import Data.Text.Lazy as LText
    import Data.Text as Text
    import Data.Text.IO as Text

    main = Text.putStrLn $ LText.toStrict $ Builder.toLazyText $ encodeToTextBuilder $ object [Text.pack "test" .= (2 :: Int)]

If I compile and run this, it does not print anything and never terminates. The package set I have installed is Stackage 2.1. The only unusual thing about my GHC install is that it is compiled with `integer-simple` instead of `integer-gmp`. If I call `encode` instead of `encodeToTextBuilder`, this problem does not happen. Can anyone reproduce this issue?

-- EDIT

Some more information. It only happens when trying to encode numbers (I'm not sure which kinds of numbers though). For example, if you replace `main` with the following:

    main = Text.putStrLn $ LText.toStrict $ Builder.toLazyText $ encodeToTextBuilder $ object [Text.pack "test" .= Text.pack "bla"]

Then it doesn't hang. It renders `{"test":"bla"}` as it should.

**Comment by andrewthad** [comment]
yesodweb/yesod#967

**Comment by zeitgeist** [comment]
I stumbled upon the very same issue some time ago. For reasons unknown to me, I did not file a bug report. :(

**Comment by andrewthad** [comment]
Thank goodness it isn't just me.

**Comment by zeitgeist** [comment]
@andrewthad I was using our company's build infrastructure, that is plain old GHC 7.8.4 compiled from sources w/ integer-simple

**Comment by andrewthad** [comment]
Oh, so it's almost certainly a problem with it being incompatible with integer-simple. Either that or there's a bug in integer-simple.

**Comment by andrewthad** [comment]
Or more likely in `scientific`.

**Comment by basvandijk** [comment]
It's not `scientific` it's the `decimal` builder in `text` that is causing an infinite loop:

1. `encodeToTextBuilder` [calls](https://github.com/bos/aeson/blob/master/Data/Aeson/Encode.hs#L102) `decimal` on the `Integer` coefficient.
2. `decimal` [has the rule](https://github.com/bos/text/blob/master/Data/Text/Lazy/Builder/Int.hs#L63):  `{-# RULES "decimal/Integer" decimal = integer 10 :: Integer -> Builder #-}`
3. In `integer` we then take [this branch](https://github.com/bos/text/blob/master/Data/Text/Lazy/Builder/Int.hs#L204): `integer 10 i = decimal i` and round and round we go...

@bos do you have an idea for a fix?

**Comment by basvandijk** [comment]
While we obviously need to fix the `decimal` builder in `text` I also realize `encodeToTextBuilder` still suffers from the large-exponent-DoS vulnerability because it [computes](https://github.com/bos/aeson/blob/master/Data/Aeson/Encode.hs#L102) the possibly extremely large Integer magnitude `10 ^ e`.

The best thing would be to just replace `fromScientific` with [scientificBuilder](http://hackage.haskell.org/package/scientific-0.3.3.8/docs/Data-Text-Lazy-Builder-Scientific.html#v:scientificBuilder) which never computes such magnitudes.

**Comment by meteficha** [comment]
I think I understand the issue, thus the fix.

The rule (2) @basvandijk identified comes from https://github.com/bos/text/commit/d9222749d685c0e11065cbebadfc43f531e74d84.  It makes sense because:
  * `integer` was optimized for `Integer`s, and
  * `integer 10 (S# i#) = decimal (I# i#)` meant that small `Integer`s (able to [fit on an Int](http://hackage.haskell.org/package/integer-gmp-1.0.0.0/docs/GHC-Integer-GMP-Internals.html#v:S-35-), note that `S#` is an `Integer` constructor from `integer-gmp` while `I#` is an `Int` constructor) had a fast path.

Almost exactly one year later, @TomMD did (part of?) the work of supporting `integer-simple`.  Commit https://github.com/bos/text/commit/513b65222ed3f3cf515bfc472f331caff7383d87 added the branch (3) that @basvandijk identified.  However, he didn't understand at the time that those special cases were just fast paths for using `Int` instead of `Integer`.  His new two branches still keep the type as `Integer`.  

The easy solution thus is removing that `#else` branch, i.e., leaving `integer`'s code as:

```haskell
integer :: Int -> Integer -> Builder
#ifdef INTEGER_GMP
integer 10 (S# i#) = decimal (I# i#)
integer 16 (S# i#) = hexadecimal (I# i#)
#endif
integer base i
    | i < 0     = singleton '-' <> go (-i)
    | otherwise = go i
...
```

One could try to tap into [`integer-simple`'s internals](https://github.com/ghc/ghc/blob/master/libraries/integer-simple/GHC/Integer/Type.hs#L39) to create a fast path for small positive integers via `Word` without too much trouble, but I don't know if trying to optimize code paths that aren't well-tested is a good idea.

@kantp, @andrewthad, could you check if what I propose above fixes this issue?

**Comment by andrewthad** [comment]
I'll give it a shot right now.

**Comment by andrewthad** [comment]
@meteficha Your suggested edit works. I'll put up a PR against `text`.

**Comment by andrewthad** [comment]
Also, thanks to everyone involved in tracking this down. I am super impressed and very grateful.

**Comment by meteficha** [comment]
Thanks!  I've also sent pull request #249 to fix the vulnerability @basvandijk found.

**Comment by kantp** [comment]
Thanks a lot!
