### ISSUE TITLE
Instances for `Map Int a`

### ISSUE THREAD

**Issue by andrewthad** [bos/aeson#259]
There are already `FromJSON`/`ToJSON` instances for `IntMap` (which are super weird, given that they don't actually encode it as a JSON object), but I was wondering if we could get instances:

    instance FromJSON a => FromJSON (Map Int a)
    instance ToJSON a => ToJSON (Map Int a)

I can put up a PR if it would be accepted, but I'd like to know if it would be ok to actually use a JSON object. That is, could the JSON be like this:

    {6: "foo", 8: "bar", 1: "baz"}

instead of this:

    [[6,"foo],[8,"bar"],[1,"baz"]]

**Comment by imz** [comment]
If I'm not mistaken, the keys in JSON must be strings. (I'm almost completely sure about this, because I've checked this several times in the past.) Therefore your example is invalid.

You could format the numbers as strings for your goal.

I had a similar (more generic) wish, written down at [How to implement toJSON for an assoc-list producing an object with key-values pairs generically?](http://stackoverflow.com/q/29282244/94687).

**Comment by imz** [comment]
See also [A general serializer for Data.Map](https://github.com/bos/aeson/issues/79).

**Comment by andrewthad** [comment]
Dang, you are right. I didn't realize the JSON maps could only have string keys. The generic serializer seems interesting. I'm all for it if it's ever seriously considered for aeson.
