### ISSUE TITLE
tag gets overwritten for sum types that include a tag field

### ISSUE THREAD

**Issue by thomasdziedzic** [bos/aeson#295]
Using aeson 0.10.0.0

```
{-# LANGUAGE DeriveGeneric #-}
import GHC.Generics
import Data.Aeson
import qualified Data.ByteString.Lazy.Char8 as BLC

data Number
  = One { tag :: String }
  | Two { tag :: String }
  deriving (Generic, Show)

instance ToJSON Number

main :: IO ()
main = BLC.putStrLn $ encode $ One "Two"
```
prints out ```{"tag":"Two"}``` which will lead to a misclassification of the sum type

**Comment by basvandijk** [comment]
This is expected behaviour which might not be documented that well. 

You can fix it by configuring the generic decoder to use a different `tagFieldName ` for example

```haskell
instance ToJSON Number where
  toJSON = genericToJSON defaultOptions
                         {sumEncoding = defaultTaggedObject
                                        {tagFieldName = "constructor"}}
```

With this your program will print: `{"constructor":"One","tag":"Two"}`.

This behaviour is documented in [TaggedObject](http://hackage.haskell.org/package/aeson-0.10.0.0/docs/Data-Aeson-Types.html#v:TaggedObject).
