### ISSUE TITLE
Do not `truncate` `Integral` values

### ISSUE THREAD

**Issue by nkaretnikov** [bos/aeson#317]
aeson-0.10.0.0 `truncate`s `Integral` values like `Int`, `Integer`, etc. when converting from JSON:
```
instance FromJSON Integer where
    parseJSON = withScientific "Integral" $ pure . truncate

[...]
 
parseIntegral :: Integral a => String -> Value -> Parser a
parseIntegral expected = withScientific expected $ pure . truncate
```

I cannot test the latest version right now, but here's 0.9.0.1, which uses `floor`:
```
Prelude Data.Aeson> decode "3.14" :: Maybe Int
Just 3
```

The expected result is `Nothing` (or maybe an error message warning about the extra `.14` bit).

**Comment by bos** [comment]
@basvandijk I think this bug is valid.

**Comment by phadej** [comment]
@bergmark wouldn't fixing this be breaking change?

**Comment by nkaretnikov** [comment]
@phadej There's PVP for that.

**Comment by phadej** [comment]
@nkaretnikov there is; but if plan for 0.11 is to "unbreak" 0.10, then maybe this should wait till 0.12?

**Comment by nkaretnikov** [comment]
@phadej not a blocker for me since I'm not planning to use aeson in the near future.

**Comment by bergmark** [comment]
Right; this is potentially breaking unfortunately, so I vote for solving this after 0.11 has shipped.

**Comment by hvr** [comment]
@nkaretnikov 

btw, what should be the expected result for

```
decode "3.0000" :: Maybe Int
```

?

I'm skeptical about this one, because JSON suffers from its  JavaScript heritage which has no proper notion of integrals, since its number type is effectively a `Double`, which happens to embed 54bit integers, together with JavaScript providing some level of support for the 32bit integer subset... or something like that... so I'm not sure if it's sensible to be overly strict about floating point vs integer, when you're interoperating with other JSON implementations which follow Javascript's number data-model and therefore may emit `.0`s ...

**Comment by phadej** [comment]
@hvr with current `Scientific` implementation we don't know how the number was represented (textually) at `parseJSON` phase: `3.0000` or `3` or `30e-1` are all the same.

**Comment by andrewthad** [comment]
I've never had a problem with this, but for what it's worth, I also consider the current behavior to be a bug. I would consider the correct behavior to be:

    >>> decode "3" :: Maybe Int
    Just 3
    >>> decode "3.14" :: Maybe Int
    Nothing
    >>> decode "3.00" :: Maybe Int
    Just 3

**Comment by phadej** [comment]
Related issue is:
```hs
λ > decode "-1" :: Maybe Word8
Just 255
λ > decode "300" :: Maybe Word8
Just 44
```

So sacrificing some (a lot?) performance, we could change
```diff
-parseIntegral :: Integral a => String -> Value -> Parser a
+parseIntegralBounded :: (Integral a, Bounded a) => String -> Value -> Parser a
```
