### ISSUE TITLE
Discrepancy in `ToJSON (Either a b)` in lts-4.1 for stackage

### ISSUE THREAD

**Issue by echatav** [bos/aeson#331]
Hi, the aeson instances for `Either a b` are inconsistent between versions of aeson on github and lts-4.1 on whether the tag is upper-cased or not, e.g.

```
{"right":{"tag":"JsonResult","json":"responseJson"}}
```

vs.

```
{"Right":{"tag":"JsonResult","json":"responseJson"}}
```

This may break people's code.

**Comment by bergmark** [comment]
aeson 0.9: Right
aeson 0.10: right
aeson 0.11: Right

So it probably already broke people's code and might do again, but some packages have stayed with aeson 0.9 waiting for 0.11 so I'm not sure there's a best solution here. I'll e-mail Bryan, hopefully we can make a conscious decision before 0.11 ships.

**Comment by hvr** [comment]
IMHO: 0.11 shall go back to 0.9 semantics, as many of us are expecting a smooth upgrade path from 0.9 to 0.11 (skipping 0.10);  

If there's *really* demand, the `FromJSON` instance could tolerate accepting a lower-case `"right"` so that aeson-0.11 can read aeson-0.10 serialised data... assuming there's no other breaking change which thwarts this

**Comment by codygman** [comment]
@hvr :+1:

**Comment by bergmark** [comment]
I was leaning towards keeping the 0.9 format as well so let's do that. I've added a regression test to make sure Left/Right stay uppercase.
