### ISSUE TITLE
Removing the (Foldable t, ToJSON a) => ToJSON (t a) instance

### ISSUE THREAD

**Issue by ondrap** [bos/aeson#349]
I got burned by this several times in a row. In general, the FromJSON/ToJSON instance should strive for

    decode . encode = Just 

The `Foldable` instance doesn't keep this promise for anything other than something isomorphic to List. It tends to get called e.g. for `Data.Map` - which happens to be `Foldable`, and the result generally is not what one would expect. I got burned by this in some `Generics` programming, where my data happened to be `Foldable` and GHC insisted on using the `Foldable` instance instead of the one I provided.

**Comment by bergmark** [comment]
I wasn't aware of this instance and I agree that it's bad, it's too general.

 it seems it was an undocumented change that was introduced in v0.10: 692ed3c52356841553e8e2979a2348ed27d00b32

it would be nice to get this fixed before the 0.11 release since it will revert several changes from 0.10, pull requests welcome!
