### ISSUE TITLE
Aeson fails to parse JSON with a BOM

### ISSUE THREAD

**Issue by MichaelBurge** [bos/aeson#389]
The Authorize.NET API seems to include a BOM in its response. Aeson fails to parse such a JSON.

Steps to replicate:

1. `let text = "\65279{\"messages\":{\"resultCode\":\"Error\",\"message\":[{\"code\":\"E00003\",\"text\":\"The element 'getHostedProfilePageRequest' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' has invalid child element 'customerProfileId' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'. List of possible elements expected: 'merchantAuthentication' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'.\"}]}}"`

2. `import qualified Data.Text as T`
3. `import qualified Data.Text.Encoding as T`
4. `import Data.Attoparsec.ByteString`
5. `import Data.Aeson`
6. `parse json' $ T.encodeUtf8 $ T.pack text`

This yields the error:

> Fail "\239\187\191{\"messages\":{\"resultCode\":\"Error\",\"message\":[{\"code\":\"E00003\",\"text\":\"The element 'getHostedProfilePageRequest' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' has invalid child element 'customerProfileId' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'. List of possible elements expected: 'merchantAuthentication' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'.\"}]}}" [] "Failed reading: not a valid json value"

Removing just the "\65279" portion of the text then gives success:

> Done "" (Object (fromList [("messages",Object (fromList [("resultCode",String "Error"),("message",Array [Object (fromList [("text",String "The element 'getHostedProfilePageRequest' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' has invalid child element 'customerProfileId' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'. List of possible elements expected: 'merchantAuthentication' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'."),("code",String "E00003")])])]))]))

**Comment by hvr** [comment]
I've got bad news and good news:

The bad news is that as usual Windows blatantly violates standards (makes you wonder why even bother to write down specs). a BOM in UTF8 is stupid stupid stupid period. This trips up many implementations which rightfully don't expect a BOM, and a JSON parser complaining about this UTF8-BOM stupidity in an attempt to put and end to to this stupidity is a perfectly standards-compliant parser.

The good news though is that the latest JSON incarnation even though clearly stating that **Implementations MUST NOT add a byte order mark to the beginning of a JSON text.** also concedes 
**implementations that parse JSON texts MAY ignore the presence of a byte order mark rather than treating it as an error.**

However, if `aeson` does this, I'd need a way to switch to strict standards compliance, cause in my applications I need a leading BOM to be treated as a parsing error.

See also https://tools.ietf.org/html/rfc7159#section-8.1

**Comment by MichaelBurge** [comment]
I contacted Authorize.NET to see if they would remove the BOM from their API, and it's on their list. Even so, Aeson should have an option to parse such messages, since there are surely other vendors emitting BOMs. I tend to think that leniency should be the default. I think it would make sense to add:

data Options = Lenient | Strict
jsonWithOptions
decodeWithOptions

and to default json and decode to either Lenient or Strict.

Another possibility would be to not change anything, but add a 'stripBom :: ByteString -> ByteString' function that affected users could use to prepare non-compliant JSONs for parsing with Aeson. And maybe an error message suggesting to use it, if a BOM is detected.

**Comment by bergmark** [comment]
`stripBom` sounds like the better solution to me, it doesn't require any changes to aeson and we won't have to worry about what other kinds of non-standards-compliant messages are used.

**Comment by bergmark** [comment]
Similarly to #180 this is better solved externally from aeson.

**Comment by mbj** [comment]
@bergmark Thx. As a user of aeson I apprechiate you take those arguments and only handle the JSON domain, nothing else. Stripping BOMs is easy, per use case.
