### ISSUE TITLE
unwrapUnaryRecords is enabled by default, although it is not

### ISSUE THREAD

**Issue by eskimor** [bos/aeson#451]
https://hackage.haskell.org/package/aeson-0.11.2.0/docs/Data-Aeson-Types.html#v:defaultOptions

says that unwrapUnaryOptions is false by default, but it happens nevertheless.

For backwards compatibility the option in the default settings should probably be set to true when fixing the bug.

Sorry - I don't have the time right now for a PR fixing this, but as this just got reported in [purescript-argonaut-generic-codecs](https://github.com/eskimor/purescript-argonaut-generic-codecs/issues/3), it is time that this but at least gets reported.

**Comment by phadej** [comment]
There is no tests for `unwrapUnaryRecords`. That might explain why it behaves strangely.

**Comment by bergmark** [comment]
Do you have a reproduction of this?

```haskell
> data X = X { x :: Int } deriving (Generic, Show) ; instance ToJSON X where toJSON = genericToJSON defaultOptions
> encode (X 1)
"{\"x\":1}"

> data X = X { x :: Int } deriving (Generic, Show) ; instance ToJSON X where toJSON = genericToJSON defaultOptions { unwrapUnaryRecords = True }
> encode (X 1)
"1"

> data X = X { x :: Int } deriving (Generic, Show) ; instance ToJSON X where toJSON = genericToJSON defaultOptions { unwrapUnaryRecords = False }
> encode (X 1)
"{\"x\":1}"

```

**Comment by phadej** [comment]
@bergmark maybe double negation is confusing here *don't unwrap = wrap*

**Comment by bergmark** [comment]
Erm, so, are you saying there's a bug or not? :)

**Comment by phadej** [comment]
@bergmark, yeah. It seems it's "reversed".

**Comment by bergmark** [comment]
I disagree, I see `{\"x\":1}` as wrapped/not unwrapped/unwrap=False, the option is whether to remove the field name.

**Comment by phadej** [comment]
ah true. I said, *confusing* :)

**Comment by phadej** [comment]
(with: https://github.com/bos/aeson/issues/206 it will be even more confusing, when you will have two wrappings)

**Comment by eskimor** [comment]
From your examples it seems I just misunderstood what unwrapUnaryRecord records means. I thought it means that the data constructor X (the tag in JSON) get's removed around a record if there is only a single one, which happens in aeson- like shown in your examples. Damn - my bad.

This means the constructor gets removed anyway - regardless of any options?

Sorry about the noise then, but thanks for clearing things up!

**Comment by eskimor** [comment]
@bergmark thanks for your example code - I should already have provided one! This cleared up everything!

**Comment by robinp** [comment]
Clarifying a confusion for future readers (and self): one has to take care when automatically deriving `ToJSON` on `newtype`s, since if unwrapping happens or not depends on the enabled deriving language extensions:

For example, let's assume that someone (absolutely not me!) accidentally enables `DeriveGeneric` and `GND`:

```
> :set -XDeriveGeneric -XGeneralizedNewtypeDeriving
> newtype NaG = NaG { naG :: Int } deriving (Show, Generic, ToJSON)
> toJSON (NaG 2)
Number 2.0
```
In the above case, while a `Generic` instance is derived for `NaG`, the derived `ToJSON` instance doesn't use that, but rather `GND`. And thus the encoding matches that of the newtype-wrapped field, seemingly having the effect of unwrapping (but that was due to GND, not to Aeson's `unwrapUnaryRecords`). 

Contrast that to the case where instead of `GND`, we have `DeriveAnyClass` enabled:

```
> :set -XDeriveGeneric -XNoGeneralizedNewtypeDeriving -XDeriveAnyClass
> newtype NaG = NaG { naG :: Int } deriving (Show, Generic, ToJSON)
> toJSON (NaG 2)
Object (fromList [("naG",Number 2.0)])
```
In this case, the derived `ToJSON` will use the `Generic` instance, and the default of no-unwrap applies.
