### ISSUE TITLE
Runtime serialization error with MySQL `0000-00-00` `Day`s

### ISSUE THREAD

**Issue by parsonsmatt** [bos/aeson#484]
[The `day` function in `Data.Aeson.Encoding.Builder`](https://github.com/bos/aeson/blob/d8dafaea947f50c890a1b7327a058b4d08359d91/Data/Aeson/Encoding/Builder.hs#L188-L201) is partial, failing where the year is 0 or lesser. I'm running into this with MySQL `date` values being stored as `0000-00-00`.

There's a fairly trivial fix for this by including support for year `0000`, which is `BCE 1` according to [the wikipedia article](https://en.wikipedia.org/wiki/ISO_8601#Years). Ideally, the function could be extended to support all BCE years. At least, I'd hope that we could throw a more specific exception type than just `error`.

I'm happy to put together a patch for this issue.

**Comment by andrewthad** [comment]
I'm in favor of this change. Encoding functions should not be partial. Just to clarify, the wikipedia article indicates that way to encode years would be:

- 1 CE -> 0001
- -1 BCE -> 0000
- -2 BCE -> -0001

It would be nice (and pretty easy I think) to be a little more generous when decoding by allowing a leading plus sign so that they year could also be written as `+2016` or `2016`. @bergmark Your thoughts?

**Comment by bergmark** [comment]
I'm confused re. what the `Day` type is meant to represent. [The time docs](https://hackage.haskell.org/package/time-1.7/docs/Data-Time-Calendar.html#t:Day) say "The Modified Julian Day is a standard count of days, with zero being the day 1858-11-17." Is that a documentation error?

**Comment by bergmark** [comment]
n/m I see that this is a comment on the implementation of Day.

**Comment by bergmark** [comment]
Fixed by #486
