### ISSUE TITLE
Security Review - possible problem

### ISSUE THREAD

**Issue by eskimor** [bos/aeson#538]
I am currently checking the Haskell version for out of bounds problems, it is unsafe but looks ok. pos gets advanced at most by 1 during a fold over the input and the output is set to the same length. So it should not overflow. Except that the above is not true in one case:

https://github.com/bos/aeson/blob/master/pure/Data/Aeson/Parser/UnescapePure.hs#L164

here pos is incremented twice, once in the argument and once in the body of writeAndReturn. Is this fine - and if so why? (I don't know nothing about unicode encodings - sorry)

Could there be some crafted input that could trigger this to overflow the array?

**Comment by bergmark** [comment]
@jprider63 do you remember?

**Comment by bergmark** [comment]
Thanks a lot for doing the review!

**Comment by eskimor** [comment]
Glad it is appreciated! But I am fully egoistic here, I am using aeson in an application which has to be secure ;-)

**Comment by bergmark** [comment]
I think it's safe to assume all contributions are based on some degree of self service :)

**Comment by jprider63** [comment]
@eskimor You are referring to [this case](https://github.com/bos/aeson/blob/master/pure/Data/Aeson/Parser/UnescapePure.hs#L169)? I need to look through the details, but if I remember correctly, the output length is always less than or equal to the input length. This means you will only reach this state when you've previously consumed a byte. 

If you're interested, you can look at [these](http://bjoern.hoehrmann.de/utf-8/decoder/dfa/) [references](https://github.com/jwilm/vte/blob/master/utf8parse/src/table.rs.in) that describe the state machine. 

When I have time, I'd like to improve the performance so that this implementation is comparable to the C version. Ideally, this wouldn't end up with any unsafe code, but if it does, I'd like to try to use dependent types and/or Idris to prove there aren't any out of bounds errors.

**Comment by eskimor** [comment]
@jprider63 that would be super cool. I'll check the reference, the important thing of course is that there is no way to craft any input that would violate this assumption. But I'll check the state machine to see if this can happen. Thanks for the references!

**Comment by eskimor** [comment]
Ok, I believe it is fine because:
1. To reach this line we need the UTF state to be UtfGround with w larger than 0xffff
2. UtfGround can be reached from f directly but only with a single byte (max 0xff), other than that it has to come from decode.
3. decode can produce UtfGround in two cases
   -> in the first case it also uses a single byte as source for w - so we are fine
   -> in the second case utf state had to be UtfTail1 previously, UtfTail1 only gets produced by decode, and it is handled with the last case branch in runUtf which does not advance pos.
4. Therefore it is guaranteed that the pos only gets incremented twice, if it wasn't incremented in the previous step.

**Comment by bergmark** [comment]
Great!
