### ISSUE TITLE
Why does `()` encode and decode as the empty array?

### ISSUE THREAD

**Issue by chris-kahn** [bos/aeson#542]
I was a little surprised to find that `()` is serialized into an empty array in JavaScript, as opposed to `{}` or `null`. Is there a reason for this?

**Comment by bergmark** [comment]
Hi Chris,

I'm not sure why the choice was made originally, but one way to look at it is that `()` is a tuple of length 0, and all tuples are encoded as arrays.

I'm not fond of this choice, but at this point it may be overly disruptive to change the behavior. You can always add your own unit type with the encoding you prefer.

**Comment by chris-kahn** [comment]
The explanation about tuples makes sense, and yeah it's easy enough to create a custom unit type that returns whatever JSON I want. Thanks.

**Comment by eborden** [comment]
This is closed, but for posterity:

`()` is the multiplicative unit in the semi-ring of types. `(x, y)`, `(x, y, ())`, `((), x, y)` are "isomorphic" because `()` does not encode any useful information for a product type. In this sense `{}` is a much more appropriate type to encode `()` since `{}` is the multiplicative unit of JavaScript objects.

I understand the argument for backwards compatibility. Just providing an alternate view than the tuple encoding.

**Comment by phadej** [comment]
In Haskell we have 
- "products": positional arguments, arrays, `Foo Int Int`
- "records": named arguments, objects, `Bar { x :: Int, y :: Int }`

Unfortunately they coincide in the nullary case, `data Foo = Foo` is the same as `data Foo = Foo {}`. (And e.g. `GHC.Generics` don't let you tell the used surface syntax apart). And Haskell defaults to positional. `()` is a "product", not a "record". So the right unit is `[]`, not `{}`.

**Comment by eborden** [comment]
@phadej `[]` makes sense as a unit for the array encoding of tuples if `,` is `Array.prototype.concat`, but it is not. `',` is inclusion in the type, '(x, y, ()) = [x, y, []]` not `[x, y]`. At this point we get down to whether `{}` or `[]` carry more information, I'd argue that `[]` carries more information since it is a subtype of `{}` that encodes the behavior of an array over `{}`.

This also gets into whether there is a real distinction between products and records in Haskell. In my view (this may be naive) records are just products with tagged fields and blessed syntax, there is really no other distinction.
