### ISSUE TITLE
Can't use .= operator to build JSON because of ambiguous instances.

### ISSUE THREAD

**Issue by LeifW** [bos/aeson#651]
I put up a gist: https://gist.github.com/LeifW/f3e51437f4494eff9d7c23355f268ef7

Essentially, this file
```haskell
{-# LANGUAGE OverloadedStrings  #-}

import Data.Aeson 

thing = object [ "foo" .= "bar" ]
```
gives this error message when you try to compile it:
```
test.hs:5:18: error:
    • Ambiguous type variable ‘v0’ arising from a use of ‘.=’
      prevents the constraint ‘(ToJSON v0)’ from being solved.
      Probable fix: use a type annotation to specify what ‘v0’ should be.
      These potential instances exist:
        instance ToJSON DotNetTime
          -- Defined in ‘aeson-1.3.1.1:Data.Aeson.Types.ToJSON’
        instance ToJSON Value
          -- Defined in ‘aeson-1.3.1.1:Data.Aeson.Types.ToJSON’
        instance (ToJSON a, ToJSON b) => ToJSON (Either a b)
          -- Defined in ‘aeson-1.3.1.1:Data.Aeson.Types.ToJSON’
        ...plus 25 others
        ...plus 55 instances involving out-of-scope types
        (use -fprint-potential-instances to see them all)
    • In the expression: "foo" .= "bar"
      In the first argument of ‘object’, namely ‘["foo" .= "bar"]’
      In the expression: object ["foo" .= "bar"]
  |
5 | thing = object [ "foo" .= "bar" ]
  |                  ^^^^^^^^^^^^^^

test.hs:5:27: error:
    • Ambiguous type variable ‘v0’ arising from the literal ‘"bar"’
      prevents the constraint ‘(Data.String.IsString
                                  v0)’ from being solved.
      Probable fix: use a type annotation to specify what ‘v0’ should be.
      These potential instances exist:
        instance Data.String.IsString Value
          -- Defined in ‘aeson-1.3.1.1:Data.Aeson.Types.Internal’
        instance (a ~ Char) => Data.String.IsString [a]
          -- Defined in ‘Data.String’
        ...plus 11 instances involving out-of-scope types
        (use -fprint-potential-instances to see them all)
    • In the second argument of ‘(.=)’, namely ‘"bar"’
      In the expression: "foo" .= "bar"
      In the first argument of ‘object’, namely ‘["foo" .= "bar"]’
  |
5 | thing = object [ "foo" .= "bar" ]
```
It works in the repl and/or if you add `ExtendedDefaultRules`, though.

**Comment by Lysxia** [comment]
You can annotate `"bar"` with its type, for example, `"bar" :: Data.Text.Text`.

**Comment by tolysz** [comment]
https://kseo.github.io/posts/2017-01-04-type-defaulting-in-haskell.html

ghci adds:
```haskell
{-# LANGUAGE ExtendedDefaultRules #-}
```

**Comment by LeifW** [comment]
I ended up going wtih `object ["x" .= String "foo", "y" .= Number 10]` (though at that point the `ToJSON` constraint on `.=` is unnecessary). I think it'd be nice if that syntax were usable without those things (explicit type annotations on every value, or ExtendedDefaultRules (which I would add the no-warn-defaults flag to)) - would that be possible?

**Comment by bergmark** [comment]
I don't think there is a way to change `.=` to avoid these ambiguities since they are introduced partially outside of the library. The intended use case is for any values that have a ToJSON instance, not just literals. These things pop up a lot with OverloadedStrings and polymorphic functions, e.g. `'x' `elem` "x"` is also ambiguous. Maybe there is some way to define a new operator using closed type families but I'm not sure how useful it'd be.

You might be interested in [aeson-qq](https://hackage.haskell.org/package/aeson-qq). `object [ "foo" .= "bar" ]` = `[aesonQQ| {"foo": "bar"} |]`

Another workaround for string literals is to define `t :: Text -> Text; t = id`; `x .= t "foo"` is a bit shorter.

Yet another one, which I don't recommend, is to use RebindableSyntax and define `fromString = Text.unpack`

**Comment by bergmark** [comment]
I think we can close this.
