### ISSUE TITLE
Benchmarks depend on json-builder which is broken with GHC-8.4+

### ISSUE THREAD

**Issue by AndreasPK** [bos/aeson#667]
See https://github.com/lpsmith/json-builder/issues/2

I tried to contact the auther but since there was no response I don't expect that package to get fixed any time soon.

**Comment by bergmark** [comment]
We could try to get a [non-maintainer upload](https://github.com/haskell-infra/hackage-trustees/blob/master/policy.md#3-source-changes-simple-patches) for it.

But i'm not sure how useful these benchmarks are anymore since json-builder isn't well used or maintained, so we could disable them on GHC 8.4 or just remove them.

**Comment by bergmark** [comment]
Fixed by @phadej!
