### ISSUE TITLE
Aeson cannot parse a symbol like "ƒ"

### ISSUE THREAD

**Issue by wind2412** [bos/aeson#681]
I use aeson to parse some json files but I met a problem when parsing "ƒ" symbol in these files.

```Haskell
> Prelude Data.Aeson Data.ByteString.Lazy.Char8> decode $ pack "\"str\"" :: Maybe String
Just "str"                          (right)
> Prelude Data.Aeson Data.ByteString.Lazy.Char8> decode $ pack "\"strƒ\"" :: Maybe String
Nothing                            (wrong)
> Prelude Data.Aeson Data.ByteString.Lazy.Char8> decode $ pack "\"str😂\"" :: Maybe String
Just "str\STX"                 (right)
```

I am not very familiar with encoding, so I'm asking for help. Thanks in advance!

**Comment by Lysxia** [comment]
Hi! The problem is that the `Data.ByteString.Lazy.Char8` module assumes your `String` `"\"strƒ\""` is an ASCII string, but of course `ƒ` is not ASCII. There are no guarantees made about what non-ASCII strings encode to using `Char8.pack` , so that's why the last example succeeds, but the result is not what one would expect (`\STX` is not the emoji `😂` in any way).

You need to replace `pack` by a UTF-8 encoder, which you can get via `text`, see [Data.Text.Encoding](https://hackage.haskell.org/package/text-1.2.3.1/docs/Data-Text-Lazy-Encoding.html).

```haskell
> decode $ encodeUtf8 $ pack "\"strƒ\"" :: Maybe String
Just "str\402"
> decode $ encodeUtf8 $ pack "\"str😂\"" :: Maybe String
Just "str\128514"
```

```haskell
Data.Text.Lazy.Encoding.encodeUtf8 :: Text -> ByteString  -- both lazy
Data.Text.Lazy.pack :: String -> Text
```

**Comment by wind2412** [comment]
@Lysxia It succeeds, thanks for your help! I'll close this issue.
