### ISSUE TITLE
Upgrade time dependency

### ISSUE THREAD

**Issue by Sir4ur0n** [bos/aeson#691]
Hi,

This is my first time struggling with dependency consistency in Haskell (I use Stack), I hope this is the right way to go, otherwise I apologize.

I wish to use `time-1.9.2`+ version in my project (some nice new features like `addLocalTime` or `secondsToNominalDiffTime`), unfortunately there is no Stack snapshot using it.

I then tried to override this dependency version in my Stack resolver (`extra-deps`), unfortunately this is not possible because Aeson's dependency is `time (>=1.4 && <1.9)`

Is there a reason for this `<1.9` constraint in your code? If not, would you mind bumping the version?

Thanks for your help!

**Comment by bergmark** [comment]
time is bundled with ghc so it can be tricky to upgrade it. ghc-8.6.3 uses time-1.8.0.2 so that's why e.g. stackage nightly isn't using it yet. I would recommend staying on 1.8.x until there is a GHC release.

I just tried to do the update in aeson locally using cabal new-build but I couldn't get a working install plan, so unfortunately we may have to wait.

**Comment by Sir4ur0n** [comment]
Thank you for your answer! I see that the upcoming [GHC 8.8.1 release](https://downloads.haskell.org/ghc/8.8.1-alpha1/docs/html/users_guide/8.8.1-notes.html) will package with `time-1.9.2`, do you confirm that the first Stack snapshot on GHC 8.8.1 will use `time-1.9.2` even for Aeson?

**Comment by bergmark** [comment]
Right, we need to update aeson before that point. I tend to wait until there's a release candidate of GHC before updating, but if someone wants to build and test against the 8.8 alpha then we can do it sooner.

**Comment by Sir4ur0n** [comment]
Thank you for your answers :) I can wait until RC/release of 8.8.1 😄
