### ISSUE TITLE
Expose JSONPathElement

### ISSUE THREAD

**Issue by luke-clifton** [bos/aeson#722]
https://github.com/bos/aeson/pull/688 exposed `<?>`, but I can't construct any values for the `JSONPathElement` argument.

**Comment by bergmark** [comment]
Sounds good!

As a workaround you can import it from `Data.Aeson.Internal` but that's not ideal.

Since the constructors are just called `Key` and `Index` I suspect there would be a lot of downstream packages that would need to be updated if we export this from `Data.Aeson`. Maybe export it from `Data.Aeson.Types`, and export `<?>` from there as well?

Alternatively we could rename the constructors to JSONKey and JSONIndex and export from `Data.Aeson`, any preference?

**Comment by luke-clifton** [comment]
My preference is that people don't import modules unqualified... however, my second preference is to just export it from `Data.Aeson.Types`.

https://github.com/bos/aeson/pull/723

**Comment by bergmark** [comment]
Yeah, qualified and/or explicit import lists would prevent this issue. Unfortunately everyone doesn't use them.
