### ISSUE TITLE
Decode to a default value when key is omitted

### ISSUE THREAD

**Issue by gaoqiankun** [bos/aeson#746]
I am writting a library and a private project these days, there are a lot of config items, some of them can be left blank (optional), the others must be explicitly provided (required). I use `Maybe` type for the optional config items,  and use the corresponding default value when it is `Nothing`. I have to either use pattern matching after decoding or use `withObject` `.:?` and `.:!` to write a custom `Parser` , it is really not very convenient. So I tried to define a data type that holds a default `Symbol`, the `Symbol` will be used to decode default value of that config item. Below is my code:
```Haskell
{-# LANGUAGE DataKinds           #-}
{-# LANGUAGE DeriveGeneric       #-}
{-# LANGUAGE KindSignatures      #-}
{-# LANGUAGE OverloadedStrings   #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeOperators       #-}


module Config ( Config(..), Def(..) ) where

import           Data.Aeson
import           Data.Proxy
import           Data.String
import           GHC.TypeLits

data Def (s :: Symbol) a = Def { unDef :: a }

instance (KnownSymbol s) => FromJSON1 (Def s) where
  liftParseJSON p ps Null = do
    let v = decode $ fromString $ symbolVal (Proxy :: Proxy s)
    maybe (fail "default value is invalid") (liftParseJSON p ps) v
  liftParseJSON p ps v    = Def <$> (p v)

instance (FromJSON a, KnownSymbol s) => FromJSON (Def s a) where
  parseJSON = parseJSON1

data Config = Config { name :: Def "nobody" String
                     , age  :: Def "20" Int
                     -- more config items
                     } deriving Generic

instance FromJSON Config

--  Tests
let config1  = fromJust (decode "{}") :: Config
-- expect: unDef (name config1) == "nobody"
-- expect: unDef (age config1) == 20 should be True
-- actual: *** Exception: Maybe.fromJust: Nothing

let config2 = either error id  (eitherDecode "{\"age\": 30}") :: Config
-- expect: unDef (name config2) == "nobody"
-- expect: unDef (age config2) == 20
-- actual: *** Exception: Error in $: parsing Config failed, key "name" not found
```

The field can be omitted in json only if the field is a `Maybe` type in Haskell, or it will produce a `key not found` error message.

Can anyone help me？Thanks a lot!

**Comment by Lysxia** [comment]
I think a better way to decompose the problem is to use higher-kinded data (HKD):

```
data Config_ f = Config
  { name :: f String
  . age :: f Int
  } deriving Generic
```

Then we get the types `Config_ Maybe` of partial configs and `Config_ Identity` of complete configs.

```
type Config = Config_ Identity
```

In particular, we can parse partial configs, taking advantage of aeson's special handling of `Maybe`:

```
instance FromJSON (Config_ Maybe)
```

IMO encoding default values in the type is an antipattern, it leaks irrelevant details into every consumer of the type. It is better to declare the defaults as a regular value:

```
defConfig :: Config
defConfig = Config
  { name :: Identity "nobody"
  , age :: Identity 20
  }
```

Now to combine the partial config that are parsed with the default above, you need a function of this type:

```
withDef :: Config -> Config_ Maybe -> Config
```

Note that `Config` is really an applicative functor (but in a different category than the usual definition). If you had the following `lift1` function, then you could easily define `withDef`

```
lift1 :: (forall a. f a -> g a -> h a) -> Config_ f -> Config_ g -> Config_ h

withDef = lift1 (\x y -> Identity (fromMaybe (runIdentity x) y))
```

This generalized applicative class can be found as [`Apply` in rank2classes](https://hackage.haskell.org/package/rank2classes-1.3.1.2/docs/Rank2.html#t:Apply) (with TH to derive it) or [`ProductB` in barbis](https://hackage.haskell.org/package/barbies-1.1.3.0/docs/Data-Barbie.html#t:ProductB) (with Generics to derive it).

In any case, you can now parse full configs, by first parsing partial configs and then completing them with `withDef`:

```
instance FromJSON Config where
  parseJSON = fmap (withDef defConfig) . parseJSON
```

**Comment by gaoqiankun** [comment]
@Lysxia Thank your! Your idea is very useful. Although it doesn't  work well for nested fields, I found that `barbies` library is working on the [nested barbies](https://github.com/jcpetruzza/barbies/pull/14), which may solve my problem, I am watching on it. Thanks again!
