### ISSUE TITLE
<stdout>: commitBuffer: invalid argument (invalid character)

### ISSUE THREAD

**Issue by vkuharsky** [bos/aeson#784]
Hello, I'm sorry for my newbie question(just trying to learn Haskell a bit): Does Aeson supports white space inside object's keys? 
I'm desperately trying to build simple json parsing application using stack version _2.3.1_ and _lts 15.14_ on _Windows 10_ machine, but every time I run it, i get output `Error in $[4961]['Перший program.exe: <stdout>: commitBuffer: invalid argument (invalid character)`

Here is my sample code:
KOATUU.hs
```haskell
import Data.Aeson
import qualified Data.Text.Lazy as LT

data KOATUU =
    KOATUU { code :: LT.Text
           , category :: LT.Text
           , name :: LT.Text
           } deriving Show


instance FromJSON KOATUU where
    parseJSON = withObject "KOATUU" $ \obj -> do
        codeL1  <- obj .: "Перший рівень"
        codeL2  <- obj .: "Другий рівень"
        codeL3  <- obj .: "Третій рівень"
        codeL4  <- obj .: "Четвертий рівень"
        cat     <- obj .: "Категорія"
        ukrName <- obj .: "Назва об'єкта українською мовою"
    
        let empty = ""
            code  = head $ filter (/= empty) [codeL4, codeL3, codeL2, codeL1]
        
        pure $ KOATUU code cat ukrName
```
Main.hs 
```haskell
import Data.Aeson
import KOATUU

main :: IO ()
main = do
    parsed <- eitherDecodeFileStrict "koatuu.json" :: IO (Either String [KOATUU])
    case parsed of 
        Left err -> putStrLn err
        Right val -> print val
```
Actual file which is causing errors is valid json utf-8 file and can be downloaded from here:
 https://data.gov.ua/dataset/d945de87-539c-45b4-932a-7dda57daf8d9/resource/296adb7a-476a-40c8-9de6-211327cb3aa1/download/koatuu.json

**Comment by Lysxia** [comment]
aeson does support fields containing spaces. The error happens at object 4961 in the toplevel array, so that means that

1. aeson successfully parsed the whole array into a Haskell `Value`
2. the error happens in the conversion from `Value` to `[KOATUU]`, and the first 4961 objects are fine.

```
Error in $[4961]['Перший program.exe: <stdout>: commitBuffer: invalid argument (invalid character)
```

There are two overlapping errors here, and I don't think they're caused by aeson.

The first error is that in this JSON file, the object at index 4961, starting at line 39690, the field `"Перший рівень"` contains a raw integer `1200000000` whereas all objects before contained a string `"0700000000"`.

In your `FromJSON` instance, the handling of `codeL1` needs to be modified to account for that.

The second error is that, when printing the error message for the above error, (`putStrLn err` in `main`), `putStrLn` itself fails, possibly because of an encoding issue, but I'm not sure of the exact cause. I can't reproduce it on GHC 8.6.4, I see:

```
Error in $[4961]['Перший рівень']: parsing Lazy Text failed, expected String, but encountered Number
```

To narrow it down, does this print as expected:

```
main = putStrLn "Перший рівень"
```

**Comment by vkuharsky** [comment]
Thanks for clear explanation.

**Comment by vkuharsky** [comment]
I'm fully recovered from that data inconsistency by converting integers to strings
```haskell
import Data.Aeson.Types
import Data.Foldable(asum)
import qualified Data.Text.Lazy.Builder as B
import qualified Data.Text.Lazy.Builder.Int as B
...
packInteger :: Integer -> LT.Text
packInteger = B.toLazyText . B.decimal
```
And then I expect integer in case where integer encountered
```haskell
codeL1 <- asum [
            obj .: "Перший рівень",
            (do num <- obj .:  "Перший рівень" :: Parser Integer 
                return $ packInteger num) ]
```
Thanks again. Not clear error message made me think of aeson bug/error.

**Comment by vkuharsky** [comment]
Regarding your question @Lysxia. `putStrLn` fails to print `Перший рівень` (lts-15.14 ghc 8.8.3, Win10 x64)

`Перший рKoatuuSqlBuilder.exe: <stdout>: commitBuffer: invalid argument (invalid character)`
